# Generated by Django 2.2.1 on 2019-06-01 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_choice_is_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='survey',
        ),
    ]
