# Generated by Django 2.2.1 on 2019-06-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190603_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': (('view_results', 'View survey results'),)},
        ),
    ]
